<a href="https://colab.research.google.com/github/Hawkking2005/DevJourney/blob/main/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import pandas as pd
df = pd.DataFrame({2014:[100.5,150.8,200.9,30000,40000],
                   2015:[12000,18000,22000,30000,45000],
                   2016:[20000,50000,70000,100000,125000],
                   2017:[50000,60000,70000,80000,90000]},
                  index = ['Madhu','Kusum','Kinshuk','Ankit','Shruthi'])
print(df)

            2014   2015    2016   2017
Madhu      100.5  12000   20000  50000
Kusum      150.8  18000   50000  60000
Kinshuk    200.9  22000   70000  70000
Ankit    30000.0  30000  100000  80000
Shruthi  40000.0  45000  125000  90000

In [45]:
print(df.index)

Index(['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruthi'], dtype='object')

In [46]:
print(df.columns)

Index([2014, 2015, 2016, 2017], dtype='int64')

In [47]:
print(df.dtypes)

2014    float64
2015      int64
2016      int64
2017      int64
dtype: object

In [48]:
print(df.shape)
print(df.size)
print(df.values)

(5, 4)
20
[[1.005e+02 1.200e+04 2.000e+04 5.000e+04]
 [1.508e+02 1.800e+04 5.000e+04 6.000e+04]
 [2.009e+02 2.200e+04 7.000e+04 7.000e+04]
 [3.000e+04 3.000e+04 1.000e+05 8.000e+04]
 [4.000e+04 4.500e+04 1.250e+05 9.000e+04]]

In [49]:
print(df.tail(2))

            2014   2015    2016   2017
Ankit    30000.0  30000  100000  80000
Shruthi  40000.0  45000  125000  90000

In [50]:
print(df.iloc[:,:2])

            2014   2015
Madhu      100.5  12000
Kusum      150.8  18000
Kinshuk    200.9  22000
Ankit    30000.0  30000
Shruthi  40000.0  45000

In [51]:
data2 = {2018:[160000,110000,500000,340000,900000]}
df2 = pd.DataFrame(data2, index = ['Madhu','Kusum','Kinshuk','Ankit','Shruthi'])
print(df2)
print(df2.empty)

           2018
Madhu    160000
Kusum    110000
Kinshuk  500000
Ankit    340000
Shruthi  900000
False

In [52]:
df3= pd.concat([df,df2], axis = 1)
print(df3)

            2014   2015    2016   2017    2018
Madhu      100.5  12000   20000  50000  160000
Kusum      150.8  18000   50000  60000  110000
Kinshuk    200.9  22000   70000  70000  500000
Ankit    30000.0  30000  100000  80000  340000
Shruthi  40000.0  45000  125000  90000  900000

In [53]:
df3.transpose()

         Madhu     Kusum   Kinshuk     Ankit   Shruthi
2014     100.5     150.8     200.9   30000.0   40000.0
2015   12000.0   18000.0   22000.0   30000.0   45000.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0

In [54]:
df3[2017]

Madhu      50000
Kusum      60000
Kinshuk    70000
Ankit      80000
Shruthi    90000
Name: 2017, dtype: int64

In [55]:
select = df3.loc[['Madhu','Ankit'],[2017,2018]]
print(select)

        2017    2018
Madhu  50000  160000
Ankit  80000  340000

In [56]:
df3.loc['Shruthi'][2016]

np.float64(125000.0)

In [57]:
df3.loc['Sumeet'] = [196.2, 37800, 52000, 78438,8852]
print(df3)

            2014     2015      2016     2017      2018
Madhu      100.5  12000.0   20000.0  50000.0  160000.0
Kusum      150.8  18000.0   50000.0  60000.0  110000.0
Kinshuk    200.9  22000.0   70000.0  70000.0  500000.0
Ankit    30000.0  30000.0  100000.0  80000.0  340000.0
Shruthi  40000.0  45000.0  125000.0  90000.0  900000.0
Sumeet     196.2  37800.0   52000.0  78438.0    8852.0

In [58]:
df3.drop(2014,axis = 1, inplace = True)

In [59]:
df3

            2015      2016     2017      2018
Madhu    12000.0   20000.0  50000.0  160000.0
Kusum    18000.0   50000.0  60000.0  110000.0
Kinshuk  22000.0   70000.0  70000.0  500000.0
Ankit    30000.0  100000.0  80000.0  340000.0
Shruthi  45000.0  125000.0  90000.0  900000.0
Sumeet   37800.0   52000.0  78438.0    8852.0

In [60]:
df3.drop('Kinshuk',axis = 0, inplace = True)
df3

            2015      2016     2017      2018
Madhu    12000.0   20000.0  50000.0  160000.0
Kusum    18000.0   50000.0  60000.0  110000.0
Ankit    30000.0  100000.0  80000.0  340000.0
Shruthi  45000.0  125000.0  90000.0  900000.0
Sumeet   37800.0   52000.0  78438.0    8852.0

In [61]:
df3.rename(index = {'Ankit':'Vivan', 'Madhu':'Shailesh'} , inplace = True)
df3

             2015      2016     2017      2018
Shailesh  12000.0   20000.0  50000.0  160000.0
Kusum     18000.0   50000.0  60000.0  110000.0
Vivan     30000.0  100000.0  80000.0  340000.0
Shruthi   45000.0  125000.0  90000.0  900000.0
Sumeet    37800.0   52000.0  78438.0    8852.0

In [62]:
df3.loc['Shailesh',2018] = 100000
df3

             2015      2016     2017      2018
Shailesh  12000.0   20000.0  50000.0  100000.0
Kusum     18000.0   50000.0  60000.0  110000.0
Vivan     30000.0  100000.0  80000.0  340000.0
Shruthi   45000.0  125000.0  90000.0  900000.0
Sumeet    37800.0   52000.0  78438.0    8852.0

In [63]:
df3.to_csv('Exercise1.csv', index = False, header = False)

In [64]:
r = pd.read_csv('Exercise1.csv', header=None)
r.index = df3.index
r.columns = df3.columns
print(r)

             2015      2016     2017      2018
Shailesh  12000.0   20000.0  50000.0  100000.0
Kusum     18000.0   50000.0  60000.0  110000.0
Vivan     30000.0  100000.0  80000.0  340000.0
Shruthi   45000.0  125000.0  90000.0  900000.0
Sumeet    37800.0   52000.0  78438.0    8852.0

Exercise 2

In [65]:
df1 = pd.DataFrame({
    'Item': ['TV', 'TV', 'TV', 'AC'],
    'Company': ['LG', 'VIDEOCON', 'LG', 'SONY'],
    'Rupees': [12000, 10000, 15000, 14000],
    'USD': [700, 650, 800, 750]
})
df1

  Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750

In [66]:
df1.loc[4] = ['Bag','Skybags',6500,75]
print(df1)

  Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750
4  Bag   Skybags    6500   75

In [67]:
max_price = df1[(df1['Company'] == 'LG') & (df1['Item'] == 'TV')]['Rupees'].max()
print("\nMaximum price of LG TV:", max_price)

Maximum price of LG TV: 15000

In [68]:
sum_products = df1['Rupees'].sum()
print("\nSum of all products:", sum_products)

Sum of all products: 57500

In [69]:
sony = df1[df1['Company'] == 'SONY']['USD'].median()
print("\nMedian USD price of Sony products:", sony)

Median USD price of Sony products: 750.0

In [71]:
import pandas as pd


data = {
    'Name': ['Aparna', 'Pankaj', 'Ram', 'Ramesh', 'Naveen', 'Krrishnav', 'Bhawna'],
    'Degree': ['MBA', 'BCA', 'M.Tech', 'MBA',None, 'BCA', 'MBA'],
    'Score': [90.0,None, 80.0, 98.0, 97.0, 78.0, 89.0]
}

df5 = pd.DataFrame(data)

In [72]:
print(df5.groupby('Degree')['Score'].max())

Degree
BCA       78.0
M.Tech    80.0
MBA       98.0
Name: Score, dtype: float64

In [74]:
df5 = df5.fillna(76)
print(df5)

        Name  Degree  Score
0     Aparna     MBA   90.0
1     Pankaj     BCA   76.0
2        Ram  M.Tech   80.0
3     Ramesh     MBA   98.0
4     Naveen      76   97.0
5  Krrishnav     BCA   78.0
6     Bhawna     MBA   89.0

In [75]:
df5 = df5.set_index('Name')
print(df5)

           Degree  Score
Name
Aparna        MBA   90.0
Pankaj        BCA   76.0
Ram        M.Tech   80.0
Ramesh        MBA   98.0
Naveen         76   97.0
Krrishnav     BCA   78.0
Bhawna        MBA   89.0

In [76]:
print(df5.groupby('Degree')['Score'].mean())

Degree
76        97.000000
BCA       77.000000
M.Tech    80.000000
MBA       92.333333
Name: Score, dtype: float64

In [77]:
count_mba = (df5['Degree'] == 'MBA').sum()
print(count_mba)

3

In [78]:
bca_mode = df5[df5['Degree'] == 'BCA']['Score'].mode()
print(bca_mode)

0    76.0
1    78.0
Name: Score, dtype: float64